// Code generated by MockGen. DO NOT EDIT.
// Source: x.go
//
// Generated by this command:
//
//	mockgen -source=x.go -destination=mocks/mock_x.go -package=mocksn
//

// Package mocksn is a generated GoMock package.
package mocksn
