// Code generated by MockGen. DO NOT EDIT.
// Source: abc.go
//
// Generated by this command:
//
//	mockgen -source=abc.go -destination=mocks/mock_abc.go -package=mocksn
//

// Package mocksn is a generated GoMock package.
package mocksn
